import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf
import json

from collections import Counter

import pandas as pd
import numpy as np

from sklearn.metrics import classification_report

from tensorflow.keras import preprocessing
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from scipy import stats

def remove_number(text):
    number_pattern = re.compile('[-+]?([0-9]*\.[0-9]+|[0-9]+)')
    #Match all digits in the string and replace them by empty string
    return number_pattern.sub(r'',text)

def remove_email(text):
    email_pattern = re.compile('[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+')
    #Match email in the string and replace them by empty string
    return email_pattern.sub(r'',text)

def remove_punctuation(text):
    punctuation_pattern=re.compile('[,@\'?\.$%?!#;&_:\"]')
    return punctuation_pattern.sub(r'',text)

def remove_signs(text):
    signs_pattern = re.compile('[-/+*|\[\](){}]')
    return signs_pattern.sub(r'',text)


train_data=pd.read_excel(r'/Users/abhaypatil/Downloads/project dataset 3.xlsx')

train_data.dropna(axis = 0, how = 'any' ,inplace=True)
train_data['Num_words_text'] = train_data['text'].apply(lambda x:len(str(x).split()))
mask = train_data['Num_words_text'] >2
train_data=train_data[mask]
max_train_sentence_length = train_data['Num_words_text'].max()

train_data['text'] = train_data['text'].apply(remove_number)
train_data['text'] = train_data['text'].apply(remove_email)
train_data['text'] = train_data['text'].apply(remove_punctuation)
train_data['text'] = train_data['text'].apply(remove_signs)

#test_data='CLINIC : A1, New Friends Soc,  DR. ASHOK N SOHONI ope vanaz’. Paud Road, Kothrud, mane NBS. D.C.H ween Pune 411 038.  Ragd. No. 48430 Ph. 8975345221 ‘or Emerue ty 7H  y & Sunday Closed      79:00 a.m. 10 12:30 p.m. & §.00 p.m. to 9:00 p.m. Saturda         Piaase apply for number on “SMINQ™ app  Name: Sakshi Pell Date: 06-12-2019 11:08 am Age’Sex: 19y /F Mobile: 8975345221 Office ID: AS2923 sie: +. Tablet Zenrid Pius: 1-1-4X5 few +  rea Beare, ZANT weve, TAT 2, Tablet Montek LC (10 & 5): 0-0-1X 10 ae  y De. hok Sohon! ard erap! tenderers SaPTT dovon.28 Ie'
#test_data='    ancnetr Diagnostic Services  vanchetl Campus, 12/2/1,  Thube Park, Shivajinagar, Pune - 411005. Tel. : 020 - 28999800, 27999999, Fax : 020 - 25539675                                               SONAWANE PRANITA RAMCHANDRA | 5@x/ Age Ff 4glyPate of Repart 1702/2014 1702103097 Referring Doctor PURAM CHETAN 000000381367 Address cAI2 > a . HAEMATOLOGY Parameter Value Normal Range HAEMOGRAM ESR HB 11.8 gidb Female: 12 - 16 g/dL Male : 14 - 18 g/dL RBC COUNT 2:76 Milv/cumm Female: 3.8 - 5B ts Male :4.5 - 6.5 Mille PACKED CELL VOLUME 33.4 % Female: 37 - 47 % : Male :40 - 54 % MCV 121.01 cumics 80.0 - 100.0 cu.mics MCH 42.75 pgms 27.0 - 32.0 pgms MCHC 35.33 % 32.0 - 36.0% TOTAL WBC COUNT 42600 fcumm 4000 - 11000 fcumm DIFFERENTIAL WHITE CELL COUNT . NEUTROPHILS 86% 40 - 75 % EOSINOPHILS 1% 1-6 % LYMPHOCYTES 8% 20 - 45 % MONOCYTES 4% 2 - 10 % ‘BASOPHILS 1% SR WESTERNGREN 17 mmr PERIPHERAL BLOOD SMEAR Platelets- Adequate 257000/Cumm COMMENTS: This report is generated by theYumizen H 500 cell counter 1 instrument. < End of Report > a DR.WIRS.JOBH SAMPADA Pathologist MD, DCP Reg. No. 37050 q Collection Date: 17/02/2018 / 19:45 ! Accoptance Date: 17/02/2018 / 19:51 + Renort Date: 7022018 120:24 \ Renart Print Date; 17/02/2018 / 20:25'
#test_data='ReferenceDrBHOME ARVIND MDFAARCSID   Collection Date   AM Registration Date   am Report Date   PM                   NIRAJ A PATIL  REPORT Ta No   PID              Age Years SexMALE               Test Description  Observed Value Biological Reference Interval TEST NAME   Glycated Hemoglobin HbAC by HPLC       gene tye oT  ea eng ARAL TER Ch TER Rg Me  fy  iemcrniieas  interpretation    HbA‘C level reflects the mean glucose concentration over previous  weeks and provides better indication of long term glycemic control  For diagnosis of Diabetes Mellitus >=  yrs of age     Increased risk for developing diabetes  sf   Diabetes  Therapeutic goals for glycemic control   Adults <  MS Toddlers and Preschoolers  <  but >   = School age  yrs  <  “s Adolescents and young adults    yrs  <  be Levels of HbAC may be low as result of shortened RBC life span in case of hemolytic anemia ra Increased HbAC values may be found in patients with polycythemia or post splenectomy patients aS  Patients with Homozygous forms of rare variant HbCCSSEESC HbAc can not be quantitated as there  is no HbA In such circumstances glycemic control can be monitored using  Plasma glucose levels or serum Fructosamine oo   eer   The Ac target should be individualized based on numerous factors such as age life expectancy a comorbid conditions duration of diabetes risk of hypog lycemia oradverseconsequences from §   Pypoaiyeemis patient motivation and adherence  Ref  ADA Standards of Medical Care in Diabetes     ~   poe  oo ae rr Ct Tee EEP RR FGI EE ge regen fT EA a ory il a eh     Dr Venkatesh Keralapurkai  MBBSDCP DNBPatt Page  of  BSS RegNo  Accreditation as per ISO  CertNo MC Refer scope www nablindia¢ org AG Diagnostics Pvt Ltd   Dr Awanti Golwilkar  MO Pathology oF   Dr Vinanti Golwilkar §  gmmanpnenrermemmenmcconeenomame                                     ce carrying forwardly ieee Dr Ajit Gols '
#test_data=' Michael Haster DMD £  Commercial St SE  Salem OR  DEAH HG  Jason Spander DOB     Applewood Dr N Salem OR   Rx Penvx sotmg Disp  Sig Take  tabs ASAP then  tab  times a day  Refils    Dispense as Whitten HI Generic Substitution Pemritted Signature of Prescrber'
#test_data ='  UNMESH ORTHOPAEDIC CLINIC ~~  Dr Atul A Patil MSOrthopaedics Consultant  Trauma FellowKatherinen Hospital Germany  Sancheti HospitalPune Pelviacetabular Fellow Parkland HospitalUSA Ph    Hip Afthrosocopy FellowHerentalsBelgium ‘  Sanjeevani Hospital Varvand Mobile’  Ph  “RK oe  Date l     Chief Complaints   CO Rt > Lt knee pain   neck pain    LBP   heel pain OE  Knee Palpation  Tenderness joint line Movements    ‘i Painful  restricted terminally Special Tests  PF stress  Investigations    XR Spondylosis  be rr   Spur — DE  PF arthrosis mild =~ i “Medicines  Tab Etoshine MR SUN x After Food race Tab Razberg mg x Before food ~c   Cap ECod plus — XX  After food  os Teegel Xt  é lweek = Physiotherapy  LS Spine Extension Exercises Core exercises Neck Scapular Exercises Knee Exercises  QH  Knee ROM VMO strengtening IFT   Ultrasound Stimulation   aaita ara a aa SAG a  AG Wal ATE Ta « gal  west et AG AN A AT ST A JPA US Hare HAT Hr                   Next Followup    ni  DP —— — iran = E mail   a p on Saturday Sunday Closed '
#test_data='SAKSHIA PATIL RT eHUSARICOLONY koTHRUD  REPORT  PING. e204108 ‘Age:47.07 Yoara Sec FEMALE,  |Peternce-Or On SADAEIA, 20)  sa soma Cotecton Date: 0410812017 06:08 AM ‘Sample Date: 40812017 08:08 am Repo Date: 9410812017 03:31 PM     Complete Blood! Count (EDTAWhote Blood, Automsted Cal Courts)  Hemoglobin, EDTA hola blood  “Tebal Laucooyiae (WBC) count Plablet count  Red bod ll court  PGV (Packad Col Volume) (MCV (Mean Corpusoular Volume)  MCH (Mean Corpuscular Haemogbin)  MCHG (Mean Carpusculsr Maerrogiobin Concasntration)  ROW (Red blood celtdistibution with) Differential Count  Neutrophils  Absolute Neutroptil  Eosinophits ‘Absolula Eosinophita  Basophile ‘Absolula Basophits  Lymphooyias Abeokie Lymphocytes  Monocytes ‘Absolula Monookas        Blological Refarenca interval Male : 4.0- 17.50 gid.  Fomale :12.3- 15.3.9  Mato & Famale: 4,000 - 19,000 fu. 180,000 - 450,000 ft.  Mate: 45-5. 106 (pl Female :4.1-5.1 x 106) pL.  Fama :35:90- 46.60% 800-9608. 215-982 pgm Ba.s55 ga. 124%  40-20% 2,000 - 7,000 4.  a,  20-500 fut *  at Pe  a 9-100 Ae.     29-40% 1,000 «3,000 ft  210% 200 1000 Au  b     epNinM Sao, MOBS, DPR ag, rio 2000 /02/3098'
test_data = remove_number(test_data)
test_data = remove_email(test_data)
test_data = remove_punctuation(test_data)
test_data = remove_signs(test_data)
print(test_data)

num_words=20000
tokenizer = Tokenizer()
tokenizer.fit_on_texts(train_data['text'].tolist())
x_test  =tokenizer.texts_to_sequences(test_data)
x_test = pad_sequences(x_test, padding='post', maxlen=50)


new_model = tf.keras.models.load_model('/Users/abhaypatil/Desktop/Project/saved model/testing')
new_model.summary()

CATEGORIES = ["Prescription", "Report"]

print("Generate predictions for all samples")
predictions = new_model.predict(x_test)
print(predictions)
predict_results = predictions.argmax(axis=1)

result=np.bincount(predict_results).argmax()
print(result)

if(result == 0):
    print('PRESCRIPTION')
else:
    print('REPORT')
